/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/R3D.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/R3D.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node_id5.geometry} material={materials['52']} position={[0, -0.256, 0.256]} scale={0.064} />
    </group>
  )
}

useGLTF.preload('/R3D.glb')
